### ISSUE TITLE
NameError: undefined local variable or method `note_store' for #<Evernote::EDAM::NoteStore::NoteList:0x007fb000e60f48>

### ISSUE THREAD

**Issue by dragonfax** [Evernote/evernote-oauth-ruby#11]
`NameError: undefined local variable or method `note_store' for #<Evernote::EDAM::NoteStore::NoteList:0x007fb000e60f48>`

This is in gem `0.2.0`. I had to revert to `0.1.8` which works fine. 

I get this error when I call `notes` or `notes?` on a NoteList. something like this.

```
1  note_list = client.note_store.findNotes(filter,0,99)
2  notes = note_list.notes
```

line 2 raises the exception, but with no stack trace of its own. This isn't happening in my code. line 1 works fine. Threw me for a loop.

**Comment by rekotan** [comment]
This should be fixed in 0.2.1.  Sorry about that.

**Comment by pymander** [comment]
Is this actually fixed?  Because I'm using 0.2.1 and still seeing the same issue.

**Comment by dragonfax** [comment]
I never updated. my gem is still depending on 0.1.8

https://github.com/dragonfax/rnote/blob/master/rnote.gemspec#L31

**Comment by pymander** [comment]
That doesn't help me.  Version 0.1.8 doesn't have the reminder stuff in NoteAttributes.

**Comment by rekotan** [comment]
I don't see this error using 0.2.1.

**Comment by algking** [comment]
i still find this errro using 0.2.1 
https://github.com/pymander/evernote-mode/issues/3

**Comment by ayman** [comment]
I'm seeing [it](http://pymander/evernote-mode#3) using 0.2.2: 

```
Waiting for the result... [4 times]
notebook xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Waiting for the result...
undefined local variable or method `note_store' for #<Evernote::EDAM::NoteStore::NoteList:0x007fe44409cba0>
Updating buffer list...
```

Gems:  

```
evernote-thrift (1.25.1)
evernote_oauth (0.2.2)
oauth (0.4.7)
```

**Comment by williamsonday** [comment]
I am seeing it in 2.2 also

Waiting for the result... [3 times]
notebook nil
Waiting for the result...
undefined local variable or method `note_store' for #<Evernote::EDAM::NoteStore::NoteList:0x803d6500>
notebook nil
Waiting for the result...
undefined local variable or method`note_store' for #Evernote::EDAM::NoteStore::NoteList:0x8053c764

Gems
evernote-thrift 1.25.1
evernote_oauth 0.2.2
oauth 0.4.7

**Comment by sbhal** [comment]
With oauth-0.4.7, evernote-thrift-1.25.1, evernote_oauth-0.2.2
I am also getting undefined local variable or method note_store' for Evernote::EDAM::NoteStore::NoteList:0x007fb6500

**Comment by jeroentbt** [comment]
Same here (oauth-0.4.7, evernote-thrift-1.25.1, evernote_oauth-0.2.2, used from within pymander/evernote-mode)

undefined local variable or method `note_store' for #Evernote::EDAM::NoteStore::NoteList:0x007fc9f1e3e3e8

**Comment by rekotan** [comment]
Could you provide code snippet that reproduces the error?

**Comment by rekotan** [comment]
OK, I've tested with evernote-mode. The problem is that it loads `evernote_oauth` gem but doesn't use `EvernoteOAuth::Client` class to create `UserStore` and `NoteStore` clients. The change below will work with this case but I recommend it to use that client class within the plugin instead of using raw thrift modules.

https://github.com/evernote/evernote-oauth-ruby/pull/17

This will be merged soon. Thanks.

**Comment by jeroentbt** [comment]
Thank you @rekotan!
